# /* ********************************************************************
#  *                                                                    *
#  *    (C) Copyright Paul Mensonides, Paul Fultz II 2003-2012.         *
#  *                                                                    *
#  *    Distributed under the Boost Software License, Version 1.0.      *
#  *    (See accompanying file LICENSE).                                *
#  *                                                                    *
#  *    See http://github.com/pfultz2/Ripple for most recent version.   *
#  *                                                                    *
#  ******************************************************************** */
#
# ifndef RIPPLE_PREPROCESSOR_RECURSION_MACHINE_H
# define RIPPLE_PREPROCESSOR_RECURSION_MACHINE_H
#
# include <ripple/config.h>
# include <ripple/debug/failure.h>
# include <ripple/facilities/split.h>
#
# /* RPP_MACHINE */
#
# if CONFIG_RIPPLE_STD
#    define RPP_MACHINE(k) \
        RPP_SPLIT(1, DETAIL_RPP_MACHINE_OUTER_A_0 k) \
        /**/
#    define RPP_MACHINE_ID() RPP_MACHINE
# endif
#
# if CONFIG_RIPPLE_STD
#    define RPP_INSTRUCTION(id) RPP_INSTRUCTION_ ## id
#    define RPP_INSTRUCTION_ID() RPP_INSTRUCTION
# endif
#
# if CONFIG_RIPPLE_STD
#    define RPP_INSTRUCTION_0xripple(id) RPP_INSTRUCTION_0xripple_ ## id
#    define RPP_INSTRUCTION_0xripple_0xstop(p, x, ...) , p ## x
# endif
#
# if CONFIG_RIPPLE_STD
#    define RPP_INSTRUCTION_0xripple_0xdetail(id) RPP_INSTRUCTION_0xripple_0xdetail_ ## id
# endif
#
# if CONFIG_RIPPLE_STD
#    define DETAIL_RPP_MACHINE_INNER_B_0(...) DETAIL_RPP_MACHINE_INNER_A_0 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_0(...) DETAIL_RPP_MACHINE_OUTER_A_1 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_1(...) DETAIL_RPP_MACHINE_INNER_A_1 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_1(...) DETAIL_RPP_MACHINE_OUTER_A_2 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_2(...) DETAIL_RPP_MACHINE_INNER_A_2 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_2(...) DETAIL_RPP_MACHINE_OUTER_A_3 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_3(...) DETAIL_RPP_MACHINE_INNER_A_3 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_3(...) DETAIL_RPP_MACHINE_OUTER_A_4 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_4(...) DETAIL_RPP_MACHINE_INNER_A_4 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_4(...) DETAIL_RPP_MACHINE_OUTER_A_5 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_5(...) DETAIL_RPP_MACHINE_INNER_A_5 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_5(...) DETAIL_RPP_MACHINE_OUTER_A_6 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_6(...) DETAIL_RPP_MACHINE_INNER_A_6 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_6(...) DETAIL_RPP_MACHINE_OUTER_A_7 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_7(...) DETAIL_RPP_MACHINE_INNER_A_7 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_7(...) DETAIL_RPP_MACHINE_OUTER_A_8 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_8(...) DETAIL_RPP_MACHINE_INNER_A_8 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_8(...) DETAIL_RPP_MACHINE_OUTER_A_9 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_9(...) DETAIL_RPP_MACHINE_INNER_A_9 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_9(...) DETAIL_RPP_MACHINE_OUTER_A_10 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_10(...) DETAIL_RPP_MACHINE_INNER_A_10 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_10(...) DETAIL_RPP_MACHINE_OUTER_A_11 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_11(...) DETAIL_RPP_MACHINE_INNER_A_11 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_11(...) DETAIL_RPP_MACHINE_OUTER_A_12 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_12(...) DETAIL_RPP_MACHINE_INNER_A_12 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_12(...) DETAIL_RPP_MACHINE_OUTER_A_13 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_13(...) DETAIL_RPP_MACHINE_INNER_A_13 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_13(...) DETAIL_RPP_MACHINE_OUTER_A_14 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_14(...) DETAIL_RPP_MACHINE_INNER_A_14 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_14(...) DETAIL_RPP_MACHINE_OUTER_A_15 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_15(...) DETAIL_RPP_MACHINE_INNER_A_15 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_15(...) DETAIL_RPP_MACHINE_OUTER_A_16 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_16(...) DETAIL_RPP_MACHINE_INNER_A_16 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_16(...) DETAIL_RPP_MACHINE_OUTER_A_17 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_17(...) DETAIL_RPP_MACHINE_INNER_A_17 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_17(...) DETAIL_RPP_MACHINE_OUTER_A_18 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_18(...) DETAIL_RPP_MACHINE_INNER_A_18 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_18(...) DETAIL_RPP_MACHINE_OUTER_A_19 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_19(...) DETAIL_RPP_MACHINE_INNER_A_19 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_19(...) DETAIL_RPP_MACHINE_OUTER_A_20 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_20(...) DETAIL_RPP_MACHINE_INNER_A_20 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_20(...) DETAIL_RPP_MACHINE_OUTER_A_21 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_21(...) DETAIL_RPP_MACHINE_INNER_A_21 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_21(...) DETAIL_RPP_MACHINE_OUTER_A_22 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_22(...) DETAIL_RPP_MACHINE_INNER_A_22 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_22(...) DETAIL_RPP_MACHINE_OUTER_A_23 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_23(...) DETAIL_RPP_MACHINE_INNER_A_23 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_23(...) DETAIL_RPP_MACHINE_OUTER_A_24 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_24(...) DETAIL_RPP_MACHINE_INNER_A_24 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_24(...) DETAIL_RPP_MACHINE_OUTER_A_25 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_25(...) DETAIL_RPP_MACHINE_INNER_A_25 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_25(...) DETAIL_RPP_MACHINE_OUTER_A_26 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_26(...) DETAIL_RPP_MACHINE_INNER_A_26 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_26(...) DETAIL_RPP_MACHINE_OUTER_A_27 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_27(...) DETAIL_RPP_MACHINE_INNER_A_27 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_27(...) DETAIL_RPP_MACHINE_OUTER_A_28 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_28(...) DETAIL_RPP_MACHINE_INNER_A_28 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_28(...) DETAIL_RPP_MACHINE_OUTER_A_29 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_INNER_B_29(...) DETAIL_RPP_MACHINE_INNER_A_29 __VA_ARGS__
#    define DETAIL_RPP_MACHINE_OUTER_B_29(...) DETAIL_RPP_MACHINE_OUTER_A_30 __VA_ARGS__
# endif
#
# if CONFIG_RIPPLE_STD
#    define DETAIL_RPP_MACHINE_INNER_A_0(p, x, f, ...) RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)
#    define DETAIL_RPP_MACHINE_OUTER_A_0(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_0(DETAIL_RPP_MACHINE_INNER_B_0(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_1(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_0(DETAIL_RPP_MACHINE_INNER_B_0(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_1(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_1(DETAIL_RPP_MACHINE_INNER_B_1(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_2(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_1(DETAIL_RPP_MACHINE_INNER_B_1(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_2(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_2(DETAIL_RPP_MACHINE_INNER_B_2(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_3(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_2(DETAIL_RPP_MACHINE_INNER_B_2(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_3(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_3(DETAIL_RPP_MACHINE_INNER_B_3(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_4(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_3(DETAIL_RPP_MACHINE_INNER_B_3(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_4(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_4(DETAIL_RPP_MACHINE_INNER_B_4(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_5(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_4(DETAIL_RPP_MACHINE_INNER_B_4(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_5(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_5(DETAIL_RPP_MACHINE_INNER_B_5(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_6(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_5(DETAIL_RPP_MACHINE_INNER_B_5(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_6(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_6(DETAIL_RPP_MACHINE_INNER_B_6(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_7(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_6(DETAIL_RPP_MACHINE_INNER_B_6(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_7(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_7(DETAIL_RPP_MACHINE_INNER_B_7(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_8(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_7(DETAIL_RPP_MACHINE_INNER_B_7(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_8(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_8(DETAIL_RPP_MACHINE_INNER_B_8(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_9(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_8(DETAIL_RPP_MACHINE_INNER_B_8(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_9(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_9(DETAIL_RPP_MACHINE_INNER_B_9(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_10(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_9(DETAIL_RPP_MACHINE_INNER_B_9(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_10(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_10(DETAIL_RPP_MACHINE_INNER_B_10(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_11(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_10(DETAIL_RPP_MACHINE_INNER_B_10(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_11(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_11(DETAIL_RPP_MACHINE_INNER_B_11(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_12(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_11(DETAIL_RPP_MACHINE_INNER_B_11(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_12(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_12(DETAIL_RPP_MACHINE_INNER_B_12(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_13(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_12(DETAIL_RPP_MACHINE_INNER_B_12(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_13(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_13(DETAIL_RPP_MACHINE_INNER_B_13(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_14(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_13(DETAIL_RPP_MACHINE_INNER_B_13(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_14(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_14(DETAIL_RPP_MACHINE_INNER_B_14(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_15(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_14(DETAIL_RPP_MACHINE_INNER_B_14(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_15(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_15(DETAIL_RPP_MACHINE_INNER_B_15(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_16(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_15(DETAIL_RPP_MACHINE_INNER_B_15(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_16(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_16(DETAIL_RPP_MACHINE_INNER_B_16(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_17(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_16(DETAIL_RPP_MACHINE_INNER_B_16(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_17(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_17(DETAIL_RPP_MACHINE_INNER_B_17(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_18(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_17(DETAIL_RPP_MACHINE_INNER_B_17(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_18(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_18(DETAIL_RPP_MACHINE_INNER_B_18(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_19(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_18(DETAIL_RPP_MACHINE_INNER_B_18(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_19(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_19(DETAIL_RPP_MACHINE_INNER_B_19(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_20(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_19(DETAIL_RPP_MACHINE_INNER_B_19(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_20(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_20(DETAIL_RPP_MACHINE_INNER_B_20(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_21(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_20(DETAIL_RPP_MACHINE_INNER_B_20(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_21(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_21(DETAIL_RPP_MACHINE_INNER_B_21(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_22(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_21(DETAIL_RPP_MACHINE_INNER_B_21(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_22(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_22(DETAIL_RPP_MACHINE_INNER_B_22(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_23(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_22(DETAIL_RPP_MACHINE_INNER_B_22(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_23(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_23(DETAIL_RPP_MACHINE_INNER_B_23(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_24(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_23(DETAIL_RPP_MACHINE_INNER_B_23(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_24(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_24(DETAIL_RPP_MACHINE_INNER_B_24(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_25(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_24(DETAIL_RPP_MACHINE_INNER_B_24(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_25(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_25(DETAIL_RPP_MACHINE_INNER_B_25(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_26(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_25(DETAIL_RPP_MACHINE_INNER_B_25(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_26(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_26(DETAIL_RPP_MACHINE_INNER_B_26(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_27(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_26(DETAIL_RPP_MACHINE_INNER_B_26(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_27(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_27(DETAIL_RPP_MACHINE_INNER_B_27(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_28(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_27(DETAIL_RPP_MACHINE_INNER_B_27(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_28(p, x, f, ...) DETAIL_RPP_MACHINE_OUTER_B_28(DETAIL_RPP_MACHINE_INNER_B_28(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_INNER_A_29(p, x, f, ...) DETAIL_RPP_MACHINE_INNER_B_28(DETAIL_RPP_MACHINE_INNER_B_28(RPP_INSTRUCTION p ## f(, p ## x, p ## __VA_ARGS__)))
#    define DETAIL_RPP_MACHINE_OUTER_A_29(p, x, f, ...) RPP_FAILURE()
# endif
#
# endif
